version: '3.3'

services:
  mongo:
    ports:
      - '27017:27017'
    container_name: mongoincidentia
    restart: unless-stopped
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=bdung
    image: mongo
  front:
    ports:
      - '80:80'
    container_name: frontincidentia
    restart: unless-stopped
    logging:
      options:
        max-size: 1g
    build: ./front/